[package]
name = "arp"
version.workspace = true
edition.workspace = true

[dependencies]
pnet = "0.35.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["sync", "macros", "rt-multi-thread"] }
leaky-bucket = "1.1.2"