[package]
name = "arp"
version.workspace = true
edition.workspace = true

[dependencies]
pnet = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "rt-multi-thread"] }
tracing = { workspace = true, features = ["log"] }
derive_more = { workspace = true, features = ["deref"] }

[dev-dependencies]
simple-log = { workspace = true }
