[package]
name = "influxdb"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
influxdb = { workspace = true }
control = { workspace = true }
tracing = { workspace = true }
