[package]
name = "macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
macros-impl = { workspace = true }
syn = { workspace = true, features = ["proc-macro"] }
